// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvVqImfnbua-Y8wkdgEH2_P-izKYrIMVQ',
    appId: '1:338040651499:web:988737fb4c6ec5f84b88ae',
    messagingSenderId: '338040651499',
    projectId: 'chatterz-4ed37',
    authDomain: 'chatterz-4ed37.firebaseapp.com',
    storageBucket: 'chatterz-4ed37.appspot.com',
    measurementId: 'G-PEQ8CGHCQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG_qD2slac5tbhzS4k0JLv8KHoF_gv-ig',
    appId: '1:338040651499:android:ccbe75346923df324b88ae',
    messagingSenderId: '338040651499',
    projectId: 'chatterz-4ed37',
    storageBucket: 'chatterz-4ed37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCede4myAvjdSrGeZf4uZ7L7PsRyAdKczA',
    appId: '1:338040651499:ios:57ed76db6f27288b4b88ae',
    messagingSenderId: '338040651499',
    projectId: 'chatterz-4ed37',
    storageBucket: 'chatterz-4ed37.appspot.com',
    iosBundleId: 'com.example.chatterz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCede4myAvjdSrGeZf4uZ7L7PsRyAdKczA',
    appId: '1:338040651499:ios:7b381f361757db854b88ae',
    messagingSenderId: '338040651499',
    projectId: 'chatterz-4ed37',
    storageBucket: 'chatterz-4ed37.appspot.com',
    iosBundleId: 'com.example.chatterz.RunnerTests',
  );
}
